/**
 * Normalized surveillance event model.
 * Source-independent: identical structure from demo video OR live camera.
 * To add a new event type, add it here — the workflow engine handles the rest.
 */

export type EventType =
  | "MOVEMENT_DETECTED"
  | "PERSON_DETECTED"
  | "VEHICLE_DETECTED"
  | "ZONE_INTRUSION";

export type EventStatus = "NEW" | "ACKNOWLEDGED" | "RESOLVED";
export type EventSource = "DEMO" | "LIVE";
export type AlertSeverity = "INFO" | "WARNING" | "CRITICAL";

/** Detection event produced by the processing pipeline — source-agnostic. */
export interface SurveillanceEvent {
  id: string;
  cameraId: string;
  type: EventType;
  description: string;
  timestamp: string;
  videoTime: number;
  confidence?: number;
  status: EventStatus;
  source: EventSource;
}

/** Operator-facing alert generated by the workflow rule engine. */
export interface SurveillanceAlert {
  id: string;
  eventId: string;
  severity: AlertSeverity;
  title: string;
  cameraId: string;
  timestamp: string;
  status: EventStatus;
  source: EventSource;
}

/** Security incident auto-created for CRITICAL workflow rule matches. */
export interface Incident {
  id: string;
  alertId: string;
  type: EventType;
  description: string;
  cameraId: string;
  timestamp: string;
  status: EventStatus;
}
